# Generated by Django 5.1.6 on 2025-03-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("draft", "Draft"),
                            ("Downloaded", "Downloaded"),
                            ("Updated", "Updated"),
                            ("published", "Published"),
                            ("Error", "Error"),
                        ],
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                ("hashtags", models.TextField()),
                ("isdub", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upload_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
