# Generated by Django 5.1.6 on 2025-03-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="upload_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
