# Generated by Django 5.1.6 on 2025-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
        ),
    ]
