# Generated by Django 5.1.6 on 2025-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfread", "0002_alter_books_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
