# Generated by Django 5.1.6 on 2025-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfread", "0003_books_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="is_reading",
            field=models.BooleanField(default=False),
        ),
    ]
