# Generated by Django 5.1.6 on 2025-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "Recipe", "verbose_name_plural": "Recipess"},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="day",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
