# Generated by Django 5.1.6 on 2025-03-06 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("credit", models.IntegerField(default=3)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        default="A+",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
