# Generated by Django 5.1.6 on 2025-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_coupon_faq_legalpage_newslettersubscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvarient",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="productvarient",
            name="value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
