# Generated by Django 5.1.6 on 2025-04-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_productvarient_name_alter_productvarient_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="business_address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="business_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
