# Generated by Django 5.1.6 on 2025-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_vendor_business_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name_plural": "Cart Order"},
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="quitity",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="cart",
            name="paid_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
