# Generated by Django 5.1.6 on 2025-04-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_cart_options_rename_quitity_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="stauts",
            new_name="status",
        ),
    ]
