# Generated by Django 5.1.6 on 2025-03-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("lyrics", models.TextField(verbose_name="Lyrics")),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "English"), ("BN", "Bengali"), ("HN", "Hindi")],
                        default="BN",
                        max_length=2,
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
            },
        ),
    ]
